Table fact_purchase_order_line {
  purchase_order_line_key int [pk]
  description STRING
  purchase_order_key INT
  contact_person_key INT
  product_key INT
  order_date DATE
  ordered_outers INT
  received_outers INT
  expected_unit_price_per_outer NUMERIC
  ordered_outers_expected_price NUMERIC
  received_outers_expected_price NUMERIC
}


Table dim_date {
  date date [pk]
  day_of_week date
  day_of_week_short date
  is_weekday_or_weekend date
  year_month date
  month date
  year date
  year_number date
}



Table dim_person {
  person_key INT [pk]
  full_name STRING
  is_permitted_to_logon STRING
  is_external_logon_provider STRING
  is_system_user STRING 
  is_employee STRING
  is_salesperson STRING
}

Table dim_product {
  product_key INT [pk]
  product_name STRING
  brand_name STRING 
  quantity_per_outer INT
  tax_rate NUMERIC
  unit_price NUMERIC
  recommended_retail_price NUMERIC 
  supplier_key INT
  supplier_name STRING
  supplier_payment_days INT
  supplier_category_key INT
  supplier_category_name STRING
  delivery_method_key INT
  delivery_method_name STRING
  colour_key INT
  colour_name STRING
  unit_package_type_key INT
  unit_package_type_name STRING
  outer_package_type_key INT
  outer_package_type_name STRING
}

ref: fact_purchase_order_line.contact_person_key > dim_person.person_key
ref: fact_purchase_order_line.product_key > dim_product.product_key
ref: fact_purchase_order_line.order_date > dim_date.date



